# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNumber', models.IntegerField()),
                ('interviewSlot', models.CharField(max_length=50)),
            ],
        ),
    ]
