# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACES', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='interviewSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=30)),
                ('numberOfApplicants', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='applicant',
            name='interviewSlot',
            field=models.CharField(max_length=30),
        ),
    ]
